In [133]:
import pandas as pd
import numpy as np
import datetime
import importlib
import pickle

import data_utils
import model_utils
import train_utils
import evaluation
importlib.reload(data_utils)
importlib.reload(model_utils)
importlib.reload(train_utils)
importlib.reload(evaluation)

import torch
import torch.nn as nn
from torchtext.data import TabularDataset, Field, RawField, BucketIterator, Iterator

In [94]:
DEVICE = "cuda"

### read data and put in batch

In [95]:
train_data, val_data, test_data = data_utils.prep_all_data(device=DEVICE, use_holdout_test=False)

### Get models

In [13]:
m = model_utils.GRU()

### Training 

In [189]:
importlib.reload(model_utils)
importlib.reload(evaluation)
m = model_utils.GRU(pretrained_emb=True)
result = train_utils.train(train_data, val_data, m, device=DEVICE,
                          lr=1e-2, print_freq=5, max_epoch=100)
# combined at output

Epoch: 0, LR: 0.01, Train Loss: 354.2592, Val Loss: 261.3684, Val f1 0.160
Epoch: 5, LR: 0.01, Train Loss: 28.0804, Val Loss: 112.5740, Val f1 0.786
Epoch: 10, LR: 0.01, Train Loss: 4.3088, Val Loss: 107.8962, Val f1 0.804
Epoch: 15, LR: 0.01, Train Loss: 1.1608, Val Loss: 108.9237, Val f1 0.813
Epoch: 20, LR: 0.001, Train Loss: 0.6174, Val Loss: 112.3723, Val f1 0.810
Epoch: 25, LR: 0.001, Train Loss: 0.5888, Val Loss: 112.2277, Val f1 0.814


In [190]:
importlib.reload(model_utils)
importlib.reload(evaluation)
m = model_utils.GRU(pretrained_emb=True)
result = train_utils.train(train_data, val_data, m, device=DEVICE,
                          lr=1e-2, print_freq=5, max_epoch=100)

# no label feature

Epoch: 0, LR: 0.01, Train Loss: 359.1086, Val Loss: 274.7749, Val f1 0.108
Epoch: 5, LR: 0.01, Train Loss: 32.6015, Val Loss: 91.6128, Val f1 0.806
Epoch: 10, LR: 0.01, Train Loss: 5.7069, Val Loss: 92.4889, Val f1 0.810
Epoch: 15, LR: 0.01, Train Loss: 1.3579, Val Loss: 96.0780, Val f1 0.820
Epoch: 20, LR: 0.001, Train Loss: 0.7137, Val Loss: 99.0453, Val f1 0.832
Epoch: 25, LR: 0.001, Train Loss: 0.5556, Val Loss: 100.6193, Val f1 0.827
Epoch: 30, LR: 0.001, Train Loss: 0.5165, Val Loss: 100.9329, Val f1 0.827


In [188]:
importlib.reload(model_utils)
importlib.reload(evaluation)
m = model_utils.GRU(pretrained_emb=True)
result = train_utils.train(train_data, val_data, m, device=DEVICE,
                          lr=1e-2, print_freq=5, max_epoch=100)
# combine earlier

Epoch: 0, LR: 0.01, Train Loss: 346.6159, Val Loss: 258.2222, Val f1 0.185
Epoch: 5, LR: 0.01, Train Loss: 33.8614, Val Loss: 109.8342, Val f1 0.765
Epoch: 10, LR: 0.01, Train Loss: 5.1708, Val Loss: 110.6111, Val f1 0.799
Epoch: 15, LR: 0.01, Train Loss: 1.1762, Val Loss: 113.6327, Val f1 0.798
Epoch: 20, LR: 0.001, Train Loss: 0.6528, Val Loss: 116.0359, Val f1 0.802
Epoch: 25, LR: 0.001, Train Loss: 0.6125, Val Loss: 116.4868, Val f1 0.802


In [153]:
np.x[0, [1,2]]

tensor([0.4506, 1.0000])

In [152]:
x[0, [0, 2]] = 1; x

tensor([[1.0000, 0.4506, 1.0000],
        [0.3217, 0.8566, 0.3521]])

In [51]:
importlib.reload(model_utils)
importlib.reload(evaluation)
m = model_utils.GRU(pretrained_emb=True, bi=True, hidden_unit=200, device=DEVICE)
result = train_utils.train(train_data, val_data, m, device=DEVICE,
                          lr=1e-2, print_freq=5, max_epoch=100)

Epoch: 0, LR: 0.01, Train Loss: 359.8223, Val Loss: 284.5155, Val f1 0.096
Epoch: 5, LR: 0.01, Train Loss: 35.9260, Val Loss: 105.7272, Val f1 0.801
Epoch: 10, LR: 0.01, Train Loss: 6.5407, Val Loss: 97.1244, Val f1 0.809
Epoch: 15, LR: 0.01, Train Loss: 1.7006, Val Loss: 102.1771, Val f1 0.821
Epoch: 20, LR: 0.01, Train Loss: 0.8196, Val Loss: 105.7050, Val f1 0.818


In [128]:
m = model_utils.BaseModelWithLabel()

In [132]:
m.final_layer2.weight

Parameter containing:
tensor([[-0.1207, -0.0573, -0.0445,  ...,  0.0945,  0.0513,  0.0837],
        [-0.1133,  0.0192, -0.0481,  ...,  0.0215, -0.0645, -0.0524],
        [-0.1034, -0.1239,  0.0865,  ..., -0.0780,  0.1301,  0.0391],
        ...,
        [ 0.0961, -0.1303,  0.1223,  ..., -0.0046,  0.1292,  0.0418],
        [-0.1257, -0.0531, -0.1209,  ...,  0.0394,  0.0326, -0.0037],
        [-0.0158, -0.1216, -0.0354,  ...,  0.0736,  0.0911, -0.0301]],
       requires_grad=True)

### parameter searching - MLP
best model so far: 3 middle layer, 100 hidden units, dropout=0.2 at second to last layer

saved as ./data/model_checkpoints/MLP_Jan23.mdl

### Parameter Searching Bidirectional LSTM 

### Evaluation

In [1112]:
emb = nn.Embedding(10, 3)

In [1114]:
emb.weight

Parameter containing:
tensor([[-0.0974,  0.2542,  0.8995],
        [ 0.3284, -1.3262,  0.2224],
        [-0.1773, -0.5326,  0.5931],
        [-0.4633,  0.8940,  0.3648],
        [ 2.7178, -0.6496, -1.2509],
        [ 2.0111,  0.7471, -2.4884],
        [ 0.8162,  0.1524,  0.8900],
        [-0.5783, -1.2482,  1.3301],
        [-0.9398, -0.9525, -1.8860],
        [-0.1170,  0.2772,  1.4776]], requires_grad=True)

### Generate submission file for kaggle 

In [120]:
def get_submission(m, test_data):
    m.eval()
    labels = np.load("./data/labels.npy")
    final_labels = []
    for x, y, extra in test_data:
        pred = (torch.sigmoid(m((x, extra["raw_text"]))) > 0.5).int().cpu().numpy()
        batch_size, num_class = pred.shape
        for i in range(batch_size):
            pred_idx = np.arange(num_class)[(pred[i] == 1).astype('bool')] 
            if len(pred_idx) == 0:
                pred_idx = [np.argmax(pred[i]).item()]
            pred_label = [labels[j] for j in pred_idx]
            if "NO_REL" in pred_label and len(pred_label) > 1:
                pred_label.remove("NO_REL")
            final_labels.append(
                {"ID": int(extra["ID"][i]),
                 "CORE RELATIONS": " ".join(pred_label)})
    return pd.DataFrame(final_labels)

In [121]:
label_df = get_submission(m, val_data).sort_values(by="ID").set_index("ID")

In [97]:
df_test = pd.read_csv("./data/test.csv", index_col="ID")[["text", "raw_label"]]
df_train = pd.read_csv("./data/train_real.csv", index_col="ID")[["text", "raw_label"]]
df_val = pd.read_csv("./data/val.csv", index_col="ID")[["text", "raw_label"]]

In [84]:
today = datetime.datetime.now().strftime("%b%d")
label_df.to_csv("./data/submissions/{}GRU.csv".format(today))

In [123]:
x = label_df.join(df_val)

In [106]:
other = lambda x: "other"  in x
norel = lambda x: "NO_REL"  in x

In [124]:
x[(x["CORE RELATIONS"].apply(norel) | x.raw_label.apply(norel))]

CORE RELATIONS  \
ID                                                        
147                                              NO_REL   
219                                              NO_REL   
500                                              NO_REL   
634                                              NO_REL   
700                                              NO_REL   
736                                              NO_REL   
751                                              NO_REL   
951                                              NO_REL   
985                                              NO_REL   
985                                              NO_REL   
985                                              NO_REL   
985                                              NO_REL   
1016                                             NO_REL   
1016                                             NO_REL   
1016                                             NO_REL   
1016                                             NO_REL   
1027                                             NO_REL   
1027                                             NO_REL   
1027                                             NO_REL   
1027                                             NO_REL   
1031                                             NO_REL   
1039                                             NO_REL   
1055                                             NO_REL   
1120                                             NO_REL   
1120                                             NO_REL   
1120                                             NO_REL   
1120                                             NO_REL   
1313                                             NO_REL   
1436                                     movie.subjects   
1455                                             NO_REL   
...                                                 ...   
1980                                  actor.nationality   
1985                                             NO_REL   
2016                               movie.starring.actor   
2020                                             NO_REL   
2029                                     person.picture   
2032                               movie.starring.actor   
2034                               movie.starring.actor   
2049                               movie.starring.actor   
2055                                             NO_REL   
2067                                             NO_REL   
2072                                             NO_REL   
2079                                             NO_REL   
2165  movie.description movie.production_companies m...   
2214  movie.production_companies movie.rating movie....   
2252                                             NO_REL   
2401                                             NO_REL   
2858                                             NO_REL   
2950                                             NO_REL   
2950                                             NO_REL   
2950                                             NO_REL   
2950                                             NO_REL   
2959                                             NO_REL   
2991                                             NO_REL   
3003                                             NO_REL   
3032                                             NO_REL   
3036                                             NO_REL   
3062                                             NO_REL   
3081                                             NO_REL   
3243                                             NO_REL   
3272                                             NO_REL   

                                                   text  \
ID                                                        
147                                     who is in barfi   
219           how much did it take to make the avengers   
500                who is the director of ghost busters   
634                         

In [125]:
np.load("./data/label_vocab_restrict.npy")

array(['actor', 'amount', 'award', 'budget', 'by', 'category',
       'character', 'companies', 'country', 'date', 'description',
       'directed', 'director', 'genre', 'gross', 'language', 'locations',
       'media', 'movie', 'music', 'of', 'other', 'person', 'picture',
       'produced', 'production', 'rating', 'release', 'revenue', 'review',
       'showing', 'star', 'starring', 'synopsis', 'trailer', 'winning',
       'work', 'written'], dtype='<U11')